app:
  name: Spring Generic
spring:
  profiles.active: test
  main.allow-bean-definition-overriding: true
  main.allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 5MB


server:
  port: 5555
  servlet:
    context-path: /

allowed.origins: '*'
openai:
  model: gpt-3.5-turbo
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions